name: Workflow
on:
  push: 
    branches: 
      - feat

jobs:
  SAST:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set Enviroment Variables 
        run: echo "BRANCH_NAME=$¨{{ github.ref_name }}" >> $GITHUB_ENV

      - name: Validate and Configure build.gradle
        env:
          SONAR_TOKEN: $¨{{ secrets.SONAR_TOKEN }}
        run: |
          if [ -f "Dockerfile" ]; then 
            echo "Encontro el archivo Docker"
          else
            echo "no se encontro archivo Docker"
            exit 1
          fi
