name: Workflow
on:
  push: 
    branches: 
      - feat
jobs:
  BUILD:
    runs-on: ubuntu-latest 
    steps:

      - name: Aqui compilamos
        run: |
          echo 'Aqui compilamos'

  TESTING:
    runs-on: ubuntu-latest 
    steps:

      - name: se realizan pruebas
        run: |
          echo 'se realizan pruebas'

  DEPLOY:
    runs-on: ubuntu-latest 
    steps:

      - name: se realiza deploy
        run: |
          echo 'se realiza deploy'